### ISSUE TITLE
Vue functions

### ISSUE THREAD

**Issue by Yumshot** [code-biscuits/js-ts-biscuits#6]
No annotation within vue script tags whatsoever
<img src="https://i.imgur.com/sN1lhbB.png" />

**Comment by cmgriffing** [comment]
Thanks. I believe this is fixed in some 0.0.8 changes. Please update and double check for me.

**Comment by cmgriffing** [comment]
Sorry, after some testing. Vue files are still not working as expected. The latest change should actually disable it there for now.

I believe changes made to support JSON will make this work. So we will leave this issue active to track that.

**Comment by cmgriffing** [comment]
And now I'm sorry for spamming you.

It turns out this plugin won't be able to support Vue (yet, at least). I'm expecting to make a Vue specific version at some point. It will most likely also support Svelte too, but currently single file Vue components pose some issues that I need to use a different language server for I think.

0.0.10 disables JS/TS annotations in files that have a `<script` tag. HTML biscuits will continue to work there though.

I will try and remember to let you know when Vue-Biscuits is an actual thing.
